### ISSUE TITLE
239 Rejeição: Cabeçalho - Versão do arquivo XML não suportada

### ISSUE THREAD

**Issue by diegosoek** [leonardiwagner/NFeEletronica.NET#10]
Olá pessoal, em primeiro lugar parabéns pela API @leonardiwagner  foi muito útil para criação da minha integração.
Tive alguns problemas que já consegui corrigir até porque minha aplicação é web então muda um pouco a regra do negócio (assim que conseguir finalizar subo as alterações aqui).
Porém estou com o problema 239 Rejeição: Cabeçalho - Versão do arquivo XML não suportada quando tento submeter uma nota para a sefaz.
Alguém teve esse problema? Sabe como posso resolver?
Estou rodando com a versão 3.1 que acho que a 2 nem é mais aceita.
Desde já agradeço.
Um grande abraço

**Comment by leonardiwagner** [comment]
@diegosoek na hora que voce está montando o contexto, o segundo parametro é a versão, você está passando a versão 3 na chamada `NFeContexto()` ?

**Comment by diegosoek** [comment]
Olá @leonardiwagner sim, inclusive o cabeçalho dela está sendo gerado com a versão 
Esse é o cabeçalho que ela gera quando vai enviar a nota 
`<xml version="1.0" encoding="UTF-8"?><enviNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="3.10">`

**Comment by leonardiwagner** [comment]
@diegosoek cara, não tenho certeza, mas talvez os endpoints da versão 3.0 podem ser outros, dá uma olhada nisso. Eu realmente to por fora, faz tempo que não trabalho mais com NFe, mas chutaria que pode ser isso então.

Dá uma estrela no projeto pra aumentar a chance de outra pessoa ver e te responder melhor.
