### ISSUE TITLE
GerarCodigoDaNota

### ISSUE THREAD

**Issue by alanjholiveira** [leonardiwagner/NFeEletronica.NET#14]
Amigo, o ID da nota não e gerada automático, tentei usar o método GerarCodigoDaNota() que está no arquivo NotaFiscal.cs mais a nota não e gerada. saber me informar ser exite outra forma no projeto?

**Comment by alanjholiveira** [comment]
Resolvido! Encontrei o método e fiz a correção. "AssinaturaDeXml.cs"

Substituir:
 //if (!String.IsNullOrEmpty(nota.NotaId))
            //    reference.Uri = "#" + TagAssinatura + nota.NotaId;
            //else if (!String.IsNullOrEmpty(URI))
            //    reference.Uri = URI; 

Por:
if (!String.IsNullOrEmpty(nota.NotaId))
            {
                XmlAttributeCollection _Uri = doc.GetElementsByTagName(TagAssinatura).Item(0).Attributes;
                foreach (XmlAttribute _atributo in _Uri)
                {
                    if (_atributo.Name == "Id")
                        reference.Uri = "#" + _atributo.InnerText;
                       
                }

            }
            else if (!String.IsNullOrEmpty(URI))
            {
                reference.Uri = URI;
            }

**Comment by leonardiwagner** [comment]
Obrigado, se quiser enviar um PR com a correção, senão logo mais eu atualizo no código e coloco o devido crédito, obrigado @allanjhonne  !
