### ISSUE TITLE
Emissão DANFE

### ISSUE THREAD

**Issue by guilhermefmbatista** [leonardiwagner/NFeEletronica.NET#8]
Leonardi, boa tarde!
Parabéns pela biblioteca. Andei olhando o código e está bem estruturado e provavelmente irei utilizar.
Mas gostaria de saber se você pretende implantar a emissão da DANFE ou se poderia me indicar algum componente?
Abraço

**Comment by leonardiwagner** [comment]
@guilhermefmbatista nao planejo, de uma olhadinha no projeto acbr, que ele deve trabalhar com o danfe, a ideia desse projeto é ser o mais enxuto e simples possivel para integrar seu projeto com NFe, como eu disse de uma olhada no acbr para trabalhar com DANFE.
